import json
from pathlib import Path

p = Path(r'c:/Universidad/TEORÍA_DE_SEÑALES/Apuntes/Binary_detection_lab.ipynb')
with p.open('r', encoding='utf-8') as f:
    d = json.load(f)

new_md = {
    'cell_type': 'markdown',
    'metadata': {},
    'id': 'p4-md',
    'source': [
        '## 6. Punto 4: MAP vs Machine Learning (BinDetection_Lab_4.pdf)\n',
        '\n',
        'En este punto comparamos:\n',
        '- el detector MAP escalar usando una sola muestra por símbolo.\n',
        '- el detector MAP matched-filter usando la estadística $Z_k = \\frac{1}{L} \\sum_{n=0}^{L-1} r_k[n]$.\n',
        '- un clasificador de regresión logística entrenado con la estadística matched-filter.\n',
        '- un perceptrón multicapa (MLP) entrenado con la estadística matched-filter.\n',
        '- un perceptrón multicapa entrenado con el bloque completo $r_k$.\n',
        '\n',
        'Generamos un conjunto de datos simulado con etiquetas conocidas, lo separamos en entrenamiento, validación y prueba, y calculamos las métricas estándar $P_e$, $P_{FA}$, $P_M$ y $P_D$.\n',
    ]
}

new_code = {
    'cell_type': 'code',
    'execution_count': None,
    'metadata': {},
    'outputs': [],
    'id': 'p4-code',
    'source': [
        'from sklearn.model_selection import train_test_split\n',
        'from sklearn.linear_model import LogisticRegression\n',
        'from sklearn.neural_network import MLPClassifier\n',
        'from sklearn.preprocessing import StandardScaler\n',
        'from sklearn.metrics import confusion_matrix\n',
        '\n',
        '# Parámetros del experimento\n',
        'L = 8\n',
        'N_total = 30000\n',
        'rng = np.random.default_rng(2026)\n',
        '\n',
        '# Generamos el dataset simulado\n',
        'labels = rng.choice([0, 1], size=N_total, p=[0.5, 0.5])\n',
        'symbols = np.where(labels == 0, a0, a1)\n',
        'noise = rng.normal(0, sigma_eta, size=(N_total, L))\n',
        'r_blocks = symbols[:, None] + noise\n',
        'Z_blocks = r_blocks.mean(axis=1)\n',
        '\n',
        '# Particiones: entrenamiento 60%, validación 20%, prueba 20%\n',
        'X_train_full, X_temp_full, y_train, y_temp = train_test_split(\n',
        '    r_blocks, labels, test_size=0.4, stratify=labels, random_state=2026\n',
        ')\n',
        'X_val_full, X_test_full, y_val, y_test = train_test_split(\n',
        '    X_temp_full, y_temp, test_size=0.5, stratify=y_temp, random_state=2026\n',
        ')\n',
        '\n',
        'Z_train = X_train_full.mean(axis=1).reshape(-1, 1)\n',
        'Z_val = X_val_full.mean(axis=1).reshape(-1, 1)\n',
        'Z_test = X_test_full.mean(axis=1).reshape(-1, 1)\n',
        'X_train_scalar = X_train_full[:, 0].reshape(-1, 1)\n',
        'X_val_scalar = X_val_full[:, 0].reshape(-1, 1)\n',
        'X_test_scalar = X_test_full[:, 0].reshape(-1, 1)\n',
        '\n',
        'def compute_metrics(y_true, y_pred):\n',
        '    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()\n',
        '    PFA = fp / (fp + tn) if (fp + tn) > 0 else 0.0\n',
        '    PM = fn / (fn + tp) if (fn + tp) > 0 else 0.0\n',
        '    PD = tp / (tp + fn) if (tp + fn) > 0 else 0.0\n',
        '    Pe = (fp + fn) / (fp + fn + tp + tn)\n',
        '    return PFA, PM, PD, Pe\n',
        '\n',
        '# Detectores analíticos\n',
        'threshold = (a0 + a1) / 2\n',
        'y_pred_scalar = np.where(X_test_scalar[:, 0] >= threshold, 1, 0)\n',
        'y_pred_matched = np.where(Z_test[:, 0] >= threshold, 1, 0)\n',
        '\n',
        '# Regresión logística con Z_k\n',
        'logreg = LogisticRegression(random_state=2026, max_iter=1000)\n',
        'logreg.fit(Z_train, y_train)\n',
        'y_pred_logreg = logreg.predict(Z_test)\n',
        '\n',
        '# MLP con Z_k\n',
        'mlp_z = MLPClassifier(hidden_layer_sizes=(16,), activation="relu", solver="adam", max_iter=500, random_state=2026)\n',
        'mlp_z.fit(Z_train, y_train)\n',
        'y_pred_mlp_z = mlp_z.predict(Z_test)\n',
        '\n',
        '# MLP con todo el bloque r_k\n',
        'scaler = StandardScaler()\n',
        'X_train_full_scaled = scaler.fit_transform(X_train_full)\n',
        'X_val_full_scaled = scaler.transform(X_val_full)\n',
        'X_test_full_scaled = scaler.transform(X_test_full)\n',
        'mlp_full = MLPClassifier(hidden_layer_sizes=(32, 16), activation="relu", solver="adam", max_iter=500, random_state=2026)\n',
        'mlp_full.fit(X_train_full_scaled, y_train)\n',
        'y_pred_mlp_full = mlp_full.predict(X_test_full_scaled)\n',
        '\n',
        'results = {}\n',
        'for name, y_pred in [\n',
        '    ("Scalar MAP", y_pred_scalar),\n',
        '    ("Matched-filter MAP", y_pred_matched),\n',
        '    ("Logistic regression (Z)", y_pred_logreg),\n',
        '    ("MLP (Z)", y_pred_mlp_z),\n',
        '    ("MLP (full r)", y_pred_mlp_full),\n',
        ']:\n',
        '    PFA, PM, PD, Pe = compute_metrics(y_test, y_pred)\n',
        '    results[name] = {\n',
        '        "PFA": PFA,\n',
        '        "PM": PM,\n',
        '        "PD": PD,\n',
        '        "Pe": Pe,\n',
        '        "cm": confusion_matrix(y_test, y_pred),\n',
        '    }\n',
        '\n',
        'print("Resultados en el conjunto de prueba:")\n',
        'print("{:<28}{:>8}{:>8}{:>8}{:>8}".format("Detector", "P_e", "P_FA", "P_M", "P_D"))\n',
        'for name, info in results.items():\n',
        '    print("{:28}{:8.5f}{:8.5f}{:8.5f}{:8.5f}".format(name, info["Pe"], info["PFA"], info["PM"], info["PD"]))\n',
        '\n',
        'print("\nMatrices de confusión:")\n',
        'for name, info in results.items():\n',
        '    print(name)\n',
        '    print(info["cm"])\n',
        '    print()\n',
    ]
}

d['cells'].append(new_md)
d['cells'].append(new_code)
with p.open('w', encoding='utf-8') as f:
    json.dump(d, f, ensure_ascii=False, indent=2)
print('Punto 4 agregado')
